module.exports = {
  RPC_URL: process.env.RPC_URL,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHANNEL_ID: process.env.TELEGRAM_CHANNEL_ID,
  TELEGRAM_WEBHOOK_URL: process.env.TELEGRAM_WEBHOOK_URL,
  MONITOR_NEW_TOKENS: process.env.MONITOR_NEW_TOKENS === 'true',
  MONITOR_NEW_LIQUIDITY: process.env.MONITOR_NEW_LIQUIDITY === 'true',
  UNISWAP_V2_ROUTER_ADDRESS: process.env.UNISWAP_V2_ROUTER_ADDRESS,
};